### ISSUE TITLE
Height option

### ISSUE THREAD

**Issue by circa-one** [joshmcrty/Flurry#8]
Wouldn't it be better to have it automatically set the height to the length of the page? Putting this on a forum means setting a global height, which may not be the same for every page and index on the site. So there's bound to be a lot of smaller pages that have a huge empty space at the bottom due to the height being bigger than what the page actually is.

**Comment by joshmcrty** [comment]
@circa-one Flurry wasn't really intended to display falling snow over the entire page (there are plenty of scripts that do this already). My goal was for a more subtle effect that is very performant and avoids DOM manipulation as much as possible. In addition, getting the page height is not always as simple as it might seem. Flurry has no way of knowing if the page has an infinite scroll feature, if some content may be loaded asynchronously after the `window.onload` or jQuery `ready` events, etc. I made a decision to leave it up to the person implementing the plugin to decide what the height should be.

If you'd still like to try displaying the snow over the entire page top-to-bottom, you can try setting the height option after the page has loaded and the page height is known (e.g. after any advertisements, images, embeds, etc. have loaded). You could try something like this:

``` javascript
window.onload(function() {
  $('body').flurry({
    height: $(document).height()
  });
});
```

This doesn't account for if/when the page height might change from resizing the browser or whatever, but it should work on the initial page load. You might also want to adjust the `speed` option based on the height, otherwise short pages will have slowly falling snow and long pages will have snow that falls very fast.
